create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.schools (
  id bigint generated by default as identity primary key,
  name text not null,
  district text,
  city text,
  state text,
  school_type text not null default 'regular'
    check (school_type in ('regular', 'chassidish')),
  outreach_status text not null default 'Not contacted',
  last_contacted_at timestamptz,
  code text,
  code_2025 text,
  code_2024 text,
  admin text,
  email text,
  phone text,
  students integer not null default 0 check (students >= 0),
  orders_2026 integer not null default 0 check (orders_2026 >= 0),
  orders_2025 integer not null default 0 check (orders_2025 >= 0),
  orders_2024 integer not null default 0 check (orders_2024 >= 0),
  status text not null default 'Not started'
    check (status in ('Ready to order', 'In progress', 'Needs attention', 'Not started')),
  progress integer not null default 0 check (progress between 0 and 100),
  eligibility text,
  last_contact text,
  initials text,
  color text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists schools_name_code_idx on public.schools (name, code);
create unique index if not exists schools_2026_code_idx
  on public.schools (lower(code))
  where code is not null and btrim(code) <> '';
create index if not exists schools_status_idx on public.schools (status);
create index if not exists schools_email_idx on public.schools (lower(email));

create or replace function public.sync_schools_id_sequence()
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  sequence_name text;
  sequence_value bigint;
  sequence_called boolean;
  maximum_id bigint;
begin
  sequence_name := pg_catalog.pg_get_serial_sequence('public.schools', 'id');
  if sequence_name is null then
    raise exception 'public.schools.id does not have an identity sequence';
  end if;

  select coalesce(max(id), 0) into maximum_id from public.schools;
  execute pg_catalog.format('select last_value, is_called from %s', sequence_name)
    into sequence_value, sequence_called;
  perform pg_catalog.setval(
    sequence_name::regclass,
    greatest(maximum_id, sequence_value, 1),
    maximum_id > 0 or sequence_called
  );
  return maximum_id;
end;
$$;

revoke all on function public.sync_schools_id_sequence() from public;
grant execute on function public.sync_schools_id_sequence() to service_role;

select public.sync_schools_id_sequence();

alter table public.schools alter column district drop not null;
alter table public.schools alter column district drop default;
alter table public.schools alter column code drop not null;
alter table public.schools add column if not exists school_type text;
update public.schools set school_type = 'regular' where school_type is null;
alter table public.schools alter column school_type set default 'regular';
alter table public.schools alter column school_type set not null;
alter table public.schools drop constraint if exists schools_school_type_check;
alter table public.schools
  add constraint schools_school_type_check
  check (school_type in ('regular', 'chassidish'));
alter table public.schools add column if not exists outreach_status text;
alter table public.schools add column if not exists last_contacted_at timestamptz;

create table if not exists public.school_outreach_statuses (
  name text primary key check (btrim(name) <> ''),
  is_system boolean not null default false,
  sort_order integer not null default 100 check (sort_order >= 0),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists school_outreach_statuses_name_idx
  on public.school_outreach_statuses (lower(name));

insert into public.school_outreach_statuses (name, is_system, sort_order)
values
  ('Not contacted', true, 0),
  ('Sent invite', true, 10),
  ('Not interested', true, 20),
  ('Interested', true, 30),
  ('Sent', true, 40)
on conflict (name) do update
set is_system = excluded.is_system,
    sort_order = excluded.sort_order;

update public.schools set outreach_status = 'Not contacted' where outreach_status is null;
alter table public.schools alter column outreach_status set default 'Not contacted';
alter table public.schools alter column outreach_status set not null;
alter table public.schools drop constraint if exists schools_outreach_status_fkey;
alter table public.schools
  add constraint schools_outreach_status_fkey
  foreign key (outreach_status) references public.school_outreach_statuses(name);

create table if not exists public.school_outreach_status_history (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete cascade,
  status_name text not null references public.school_outreach_statuses(name),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists school_outreach_status_history_school_created_idx
  on public.school_outreach_status_history (school_id, created_at desc);

insert into public.school_outreach_status_history (school_id, status_name)
select school.id, school.outreach_status
from public.schools school
where not exists (
  select 1
  from public.school_outreach_status_history history
  where history.school_id = school.id
);

create or replace function public.record_school_outreach_status()
returns trigger
language plpgsql
as $$
begin
  if new.outreach_status is distinct from old.outreach_status then
    insert into public.school_outreach_status_history (school_id, status_name)
    values (new.id, new.outreach_status);
  end if;
  return new;
end;
$$;

drop trigger if exists record_school_outreach_status on public.schools;
create trigger record_school_outreach_status
after update of outreach_status on public.schools
for each row execute function public.record_school_outreach_status();

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'admin'
    check (role = 'admin'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_profiles alter column role set default 'admin';
alter table public.user_profiles drop constraint if exists user_profiles_role_check;
delete from public.user_profiles where role = 'school_admin';
update public.user_profiles set role = 'admin' where role = 'program_admin';
alter table public.user_profiles
  add constraint user_profiles_role_check
  check (role = 'admin');

create table if not exists public.school_contacts (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  name text,
  email text not null,
  phone text,
  title text not null default 'Program Administrator',
  is_primary boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, email)
);

create index if not exists school_contacts_school_idx on public.school_contacts (school_id);
create index if not exists school_contacts_user_idx on public.school_contacts (user_id);
create index if not exists school_contacts_email_idx on public.school_contacts (lower(email));

alter table public.school_contacts alter column name drop not null;

create table if not exists public.school_programs (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete cascade,
  program_year integer not null check (program_year between 2000 and 2200),
  school_code text,
  eligible boolean not null default true,
  eligibility_note text,
  eligibility_expires_on date,
  status text not null default 'Not started'
    check (status in ('Ready to order', 'In progress', 'Needs attention', 'Not started', 'Complete')),
  progress integer not null default 0 check (progress between 0 and 100),
  invited_at timestamptz,
  materials_downloaded_at timestamptz,
  teachers_notified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, program_year)
);

create index if not exists school_programs_year_status_idx
  on public.school_programs (program_year, status);

create table if not exists public.school_year_stats (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete cascade,
  program_year integer not null check (program_year between 2000 and 2200),
  school_code text,
  order_count integer not null default 0 check (order_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, program_year)
);

create index if not exists school_year_stats_year_idx
  on public.school_year_stats (program_year);

create table if not exists public.form_templates (
  id uuid primary key default gen_random_uuid(),
  program_year integer not null check (program_year between 2000 and 2200),
  title text not null,
  kind text not null check (kind in ('program_guide', 'order_sheet', 'family_handout', 'other')),
  description text,
  file_name text,
  storage_path text,
  version text not null default '1',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (program_year, kind, title)
);

create table if not exists public.form_submissions (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete cascade,
  program_year integer not null check (program_year between 2000 and 2200),
  template_id uuid references public.form_templates(id) on delete set null,
  submitted_by uuid references auth.users(id) on delete set null,
  title text not null,
  file_name text not null,
  storage_path text not null,
  mime_type text,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes >= 0),
  status text not null default 'submitted'
    check (status in ('draft', 'submitted', 'under_review', 'approved', 'needs_changes', 'archived')),
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  review_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists form_submissions_school_status_idx
  on public.form_submissions (school_id, status);

create table if not exists public.correspondence (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete cascade,
  contact_id uuid references public.school_contacts(id) on delete set null,
  direction text not null check (direction in ('outbound', 'inbound')),
  channel text not null default 'email' check (channel in ('email', 'phone', 'note')),
  subject text,
  body text not null,
  from_email text,
  to_email text,
  status text not null default 'draft'
    check (status in ('draft', 'queued', 'sent', 'delivered', 'failed', 'received')),
  external_message_id text,
  contacted_at timestamptz not null default now(),
  sent_at timestamptz,
  received_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists correspondence_school_created_idx
  on public.correspondence (school_id, created_at desc);
create unique index if not exists correspondence_school_external_message_idx
  on public.correspondence (school_id, external_message_id);

alter table public.correspondence add column if not exists contacted_at timestamptz;
update public.correspondence
set contacted_at = coalesce(sent_at, received_at, created_at, now())
where contacted_at is null;
alter table public.correspondence alter column contacted_at set default now();
alter table public.correspondence alter column contacted_at set not null;

create or replace function public.update_school_last_contacted_at()
returns trigger
language plpgsql
as $$
begin
  update public.schools
  set last_contacted_at = greatest(
    coalesce(last_contacted_at, new.contacted_at),
    new.contacted_at
  )
  where id = new.school_id;
  return new;
end;
$$;

drop trigger if exists update_school_last_contacted_at on public.correspondence;
create trigger update_school_last_contacted_at
after insert on public.correspondence
for each row execute function public.update_school_last_contacted_at();

create or replace function public.flag_school_reply_needed()
returns trigger
language plpgsql
as $$
begin
  if new.direction = 'inbound' then
    update public.schools
    set status = 'Needs attention'
    where id = new.school_id;
  end if;
  return new;
end;
$$;

drop trigger if exists flag_school_reply_needed on public.correspondence;
create trigger flag_school_reply_needed
after insert on public.correspondence
for each row execute function public.flag_school_reply_needed();

update public.schools school
set last_contacted_at = latest.contacted_at
from (
  select school_id, max(contacted_at) as contacted_at
  from public.correspondence
  group by school_id
) latest
where school.id = latest.school_id
  and (
    school.last_contacted_at is null
    or school.last_contacted_at < latest.contacted_at
  );

create table if not exists public.gmail_connections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  gmail_email text not null,
  encrypted_refresh_token text not null,
  history_id text,
  initial_sync_complete boolean not null default false,
  status text not null default 'connected'
    check (status in ('connected', 'syncing', 'error')),
  messages_synced integer not null default 0 check (messages_synced >= 0),
  last_synced_at timestamptz,
  last_sync_started_at timestamptz,
  last_sync_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create unique index if not exists gmail_connections_email_idx
  on public.gmail_connections (lower(gmail_email));
create index if not exists gmail_connections_sync_idx
  on public.gmail_connections (status, last_synced_at);

create or replace function public.complete_gmail_sync(
  connection_id uuid,
  imported_count integer,
  latest_history_id text,
  completed_at timestamptz
)
returns void
language sql
security definer
set search_path = public
as $$
  update public.gmail_connections
  set status = 'connected',
      initial_sync_complete = true,
      history_id = latest_history_id,
      messages_synced = messages_synced + greatest(imported_count, 0),
      last_synced_at = completed_at,
      last_sync_error = null
  where id = connection_id;
$$;
revoke execute on function public.complete_gmail_sync(uuid, integer, text, timestamptz)
  from public, anon, authenticated;
grant execute on function public.complete_gmail_sync(uuid, integer, text, timestamptz)
  to service_role;

create table if not exists public.invitation_campaigns (
  id uuid primary key default gen_random_uuid(),
  program_year integer not null check (program_year between 2000 and 2200),
  name text not null,
  subject text not null,
  body text not null,
  status text not null default 'draft'
    check (status in ('draft', 'scheduled', 'sending', 'complete', 'cancelled')),
  recipient_count integer not null default 0 check (recipient_count >= 0),
  scheduled_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (program_year, name)
);

create table if not exists public.invitation_recipients (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.invitation_campaigns(id) on delete cascade,
  school_id bigint not null references public.schools(id) on delete cascade,
  contact_id uuid references public.school_contacts(id) on delete set null,
  email text not null,
  status text not null default 'pending'
    check (status in ('pending', 'queued', 'sent', 'delivered', 'opened', 'failed', 'skipped')),
  external_message_id text,
  sent_at timestamptz,
  delivered_at timestamptz,
  opened_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (campaign_id, school_id)
);

create index if not exists invitation_recipients_campaign_status_idx
  on public.invitation_recipients (campaign_id, status);

create table if not exists public.discount_programs (
  id uuid primary key default gen_random_uuid(),
  program_year integer not null check (program_year between 2000 and 2200),
  title text not null,
  main_code text,
  mens_collection_id text,
  mens_collection_title text,
  mens_discount_type text not null default 'percentage'
    check (mens_discount_type in ('percentage', 'fixed_amount')),
  mens_discount_value numeric(10, 2) not null default 0
    check (mens_discount_value >= 0),
  boys_collection_id text,
  boys_collection_title text,
  boys_discount_type text not null default 'percentage'
    check (boys_discount_type in ('percentage', 'fixed_amount')),
  boys_discount_value numeric(10, 2) not null default 0
    check (boys_discount_value >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  usage_limit integer check (usage_limit is null or usage_limit > 0),
  applies_once_per_customer boolean not null default false,
  combines_with_order_discounts boolean not null default false,
  combines_with_product_discounts boolean not null default false,
  combines_with_shipping_discounts boolean not null default true,
  active boolean not null default false,
  shopify_discount_id text,
  shopify_status text,
  sync_status text not null default 'draft'
    check (sync_status in ('draft', 'pending', 'synced', 'error')),
  last_synced_at timestamptz,
  last_sync_error text,
  sync_job_ids jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (program_year),
  unique (shopify_discount_id),
  check (ends_at is null or starts_at is null or ends_at > starts_at),
  check (mens_discount_type <> 'percentage' or mens_discount_value <= 100),
  check (boys_discount_type <> 'percentage' or boys_discount_value <= 100)
);

insert into public.discount_programs (
  program_year,
  title,
  mens_collection_title,
  boys_collection_title
)
values (
  2026,
  '2026 Appreciation Program',
  'Pre-order men''s shirts',
  'Pre-order boys'' shirts'
)
on conflict (program_year) do nothing;

create table if not exists public.discount_school_codes (
  id uuid primary key default gen_random_uuid(),
  discount_program_id uuid not null references public.discount_programs(id) on delete cascade,
  school_id bigint not null references public.schools(id) on delete cascade,
  program_year integer not null check (program_year between 2000 and 2200),
  code text not null check (btrim(code) <> ''),
  shopify_redeem_code_id text,
  sync_status text not null default 'pending'
    check (sync_status in ('pending', 'synced', 'error', 'removed')),
  last_synced_at timestamptz,
  last_sync_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, program_year),
  unique (program_year, code)
);

create index if not exists discount_school_codes_program_status_idx
  on public.discount_school_codes (discount_program_id, sync_status);

create table if not exists public.order_submissions (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete cascade,
  program_year integer not null check (program_year between 2000 and 2200),
  form_submission_id uuid references public.form_submissions(id) on delete set null,
  title text not null,
  teacher_count integer not null default 0 check (teacher_count >= 0),
  line_item_count integer not null default 0 check (line_item_count >= 0),
  estimated_total numeric(12, 2) not null default 0 check (estimated_total >= 0),
  status text not null default 'submitted'
    check (status in ('draft', 'submitted', 'under_review', 'approved', 'queued_for_shopify', 'sent_to_shopify', 'complete', 'rejected')),
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  approved_at timestamptz,
  shopify_order_id text,
  shopify_status text,
  shopify_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists order_submissions_school_status_idx
  on public.order_submissions (school_id, status);
create index if not exists order_submissions_shopify_queue_idx
  on public.order_submissions (status)
  where status in ('approved', 'queued_for_shopify');

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'schools', 'user_profiles', 'school_contacts', 'school_programs',
    'school_year_stats', 'school_outreach_statuses',
    'school_outreach_status_history', 'form_templates', 'form_submissions',
    'correspondence', 'gmail_connections', 'invitation_campaigns', 'invitation_recipients',
    'discount_programs', 'discount_school_codes', 'order_submissions'
  ]
  loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', table_name, table_name);
    execute format(
      'create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',
      table_name,
      table_name
    );
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end;
$$;

comment on table public.schools is 'School directory plus workbook-compatible aggregate fields used by the current dashboard.';
comment on table public.school_outreach_statuses is 'Built-in and administrator-created outreach statuses available to every school.';
comment on table public.school_outreach_status_history is 'Append-only history of outreach status changes for each school.';
comment on table public.school_year_stats is 'Normalized yearly school codes and order totals for 2024, 2025, 2026, and future years.';
comment on table public.discount_programs is 'Shared Shopify discount configuration for each Appreciation Program year.';
comment on table public.discount_school_codes is 'Per-school redeem-code synchronization state for a yearly Shopify discount.';
comment on table public.order_submissions is 'Submitted order sheets and the future Shopify processing queue.';
comment on table public.correspondence is 'Complete per-school email, phone, and internal-note history.';
comment on table public.gmail_connections is 'Encrypted read-only Gmail connections and incremental synchronization state.';

grant usage on schema public to service_role;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on all functions in schema public to service_role;

alter default privileges in schema public
  grant select, insert, update, delete on tables to service_role;
alter default privileges in schema public
  grant usage, select on sequences to service_role;
alter default privileges in schema public
  grant execute on functions to service_role;
