create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.schools (
  id bigint generated by default as identity primary key,
  name text not null,
  district text,
  city text,
  state text,
  code text,
  code_2025 text,
  code_2024 text,
  admin text,
  email text,
  phone text,
  students integer not null default 0 check (students >= 0),
  orders_2026 integer not null default 0 check (orders_2026 >= 0),
  orders_2025 integer not null default 0 check (orders_2025 >= 0),
  orders_2024 integer not null default 0 check (orders_2024 >= 0),
  status text not null default 'Not started'
    check (status in ('Ready to order', 'In progress', 'Needs attention', 'Not started')),
  progress integer not null default 0 check (progress between 0 and 100),
  eligibility text,
  last_contact text,
  initials text,
  color text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists schools_name_code_idx on public.schools (name, code);
create index if not exists schools_status_idx on public.schools (status);
create index if not exists schools_email_idx on public.schools (lower(email));

alter table public.schools alter column district drop not null;
alter table public.schools alter column district drop default;
alter table public.schools alter column code drop not null;

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'school_admin'
    check (role in ('program_admin', 'school_admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.school_contacts (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  name text,
  email text not null,
  phone text,
  title text not null default 'Program Administrator',
  is_primary boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, email)
);

create index if not exists school_contacts_school_idx on public.school_contacts (school_id);
create index if not exists school_contacts_user_idx on public.school_contacts (user_id);
create index if not exists school_contacts_email_idx on public.school_contacts (lower(email));

alter table public.school_contacts alter column name drop not null;

create table if not exists public.school_programs (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete cascade,
  program_year integer not null check (program_year between 2000 and 2200),
  school_code text,
  eligible boolean not null default true,
  eligibility_note text,
  eligibility_expires_on date,
  status text not null default 'Not started'
    check (status in ('Ready to order', 'In progress', 'Needs attention', 'Not started', 'Complete')),
  progress integer not null default 0 check (progress between 0 and 100),
  invited_at timestamptz,
  materials_downloaded_at timestamptz,
  teachers_notified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, program_year)
);

create index if not exists school_programs_year_status_idx
  on public.school_programs (program_year, status);

create table if not exists public.school_year_stats (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete cascade,
  program_year integer not null check (program_year between 2000 and 2200),
  school_code text,
  order_count integer not null default 0 check (order_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, program_year)
);

create index if not exists school_year_stats_year_idx
  on public.school_year_stats (program_year);

create table if not exists public.form_templates (
  id uuid primary key default gen_random_uuid(),
  program_year integer not null check (program_year between 2000 and 2200),
  title text not null,
  kind text not null check (kind in ('program_guide', 'order_sheet', 'family_handout', 'other')),
  description text,
  file_name text,
  storage_path text,
  version text not null default '1',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (program_year, kind, title)
);

create table if not exists public.form_submissions (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete cascade,
  program_year integer not null check (program_year between 2000 and 2200),
  template_id uuid references public.form_templates(id) on delete set null,
  submitted_by uuid references auth.users(id) on delete set null,
  title text not null,
  file_name text not null,
  storage_path text not null,
  mime_type text,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes >= 0),
  status text not null default 'submitted'
    check (status in ('draft', 'submitted', 'under_review', 'approved', 'needs_changes', 'archived')),
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  review_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists form_submissions_school_status_idx
  on public.form_submissions (school_id, status);

create table if not exists public.correspondence (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete cascade,
  contact_id uuid references public.school_contacts(id) on delete set null,
  direction text not null check (direction in ('outbound', 'inbound')),
  channel text not null default 'email' check (channel in ('email', 'phone', 'note')),
  subject text,
  body text not null,
  from_email text,
  to_email text,
  status text not null default 'draft'
    check (status in ('draft', 'queued', 'sent', 'delivered', 'failed', 'received')),
  external_message_id text,
  sent_at timestamptz,
  received_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists correspondence_school_created_idx
  on public.correspondence (school_id, created_at desc);

create table if not exists public.invitation_campaigns (
  id uuid primary key default gen_random_uuid(),
  program_year integer not null check (program_year between 2000 and 2200),
  name text not null,
  subject text not null,
  body text not null,
  status text not null default 'draft'
    check (status in ('draft', 'scheduled', 'sending', 'complete', 'cancelled')),
  recipient_count integer not null default 0 check (recipient_count >= 0),
  scheduled_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (program_year, name)
);

create table if not exists public.invitation_recipients (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.invitation_campaigns(id) on delete cascade,
  school_id bigint not null references public.schools(id) on delete cascade,
  contact_id uuid references public.school_contacts(id) on delete set null,
  email text not null,
  status text not null default 'pending'
    check (status in ('pending', 'queued', 'sent', 'delivered', 'opened', 'failed', 'skipped')),
  external_message_id text,
  sent_at timestamptz,
  delivered_at timestamptz,
  opened_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (campaign_id, school_id)
);

create index if not exists invitation_recipients_campaign_status_idx
  on public.invitation_recipients (campaign_id, status);

create table if not exists public.order_submissions (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete cascade,
  program_year integer not null check (program_year between 2000 and 2200),
  form_submission_id uuid references public.form_submissions(id) on delete set null,
  title text not null,
  teacher_count integer not null default 0 check (teacher_count >= 0),
  line_item_count integer not null default 0 check (line_item_count >= 0),
  estimated_total numeric(12, 2) not null default 0 check (estimated_total >= 0),
  status text not null default 'submitted'
    check (status in ('draft', 'submitted', 'under_review', 'approved', 'queued_for_shopify', 'sent_to_shopify', 'complete', 'rejected')),
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  approved_at timestamptz,
  shopify_order_id text,
  shopify_status text,
  shopify_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists order_submissions_school_status_idx
  on public.order_submissions (school_id, status);
create index if not exists order_submissions_shopify_queue_idx
  on public.order_submissions (status)
  where status in ('approved', 'queued_for_shopify');

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'schools', 'user_profiles', 'school_contacts', 'school_programs',
    'school_year_stats', 'form_templates', 'form_submissions',
    'correspondence', 'invitation_campaigns', 'invitation_recipients',
    'order_submissions'
  ]
  loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', table_name, table_name);
    execute format(
      'create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',
      table_name,
      table_name
    );
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end;
$$;

comment on table public.schools is 'School directory plus workbook-compatible aggregate fields used by the current dashboard.';
comment on table public.school_year_stats is 'Normalized yearly school codes and order totals for 2024, 2025, 2026, and future years.';
comment on table public.order_submissions is 'Submitted order sheets and the future Shopify processing queue.';
comment on table public.correspondence is 'Complete per-school email, phone, and internal-note history.';

grant usage on schema public to service_role;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on all functions in schema public to service_role;

alter default privileges in schema public
  grant select, insert, update, delete on tables to service_role;
alter default privileges in schema public
  grant usage, select on sequences to service_role;
alter default privileges in schema public
  grant execute on functions to service_role;
